murl/README

Test PR request for Barry

---

app/app_main.c
src/acvp.c
src/acvp.h
src/acvp_drbg.c
src/acvp_lcl.h
src/acvp_util.c

Code changes per updated DRBG Spec.

Drbg updates Spec

---

src/acvp.c

Update to field name per 0.3 spec

Fix in acvp.c to use capabilityExchange instead of capability_exchange

---

src/acvp.c
src/acvp_des.c
src/acvp_hash.c

This PR addresses issues that showed up in valgrind and coverity

Tasm 419 - valgrind and coverity

---

src/acvp.h
src/acvp_lcl.h
src/acvp_rsa.c
src/acvp_util.c

Refactor RSA Key Gen to better accommodate changes for Sig Gen and Sig Ver.

Feature rsa sigver

---

app/app_main.c
src/acvp.c

adds rsa_handler app keygen processing

Rsa keygen

---

app/app_main.c

Code to implement RSA Sig Ver functionality.

RSA Sig Verify Handler

---

src/acvp_dsa.c

genG needed to be separate from genPQ.

needed to add genG to processing

---

app/app_main.c
src/acvp.c
src/acvp.h
src/acvp_aes.c
src/acvp_des.c
src/acvp_lcl.h

Still needs more testing with NIST server, but functionally working.

Initial TDES-OFB and Keywrap commit

---

app/app_main.c
src/acvp.c
src/acvp_hmac.c

Some bit/byte changes and pass the maclen to the app in case some other
app may need it.

Interop with NIST server for HMAC

---

app/app_main.c
src/acvp.c
src/acvp_aes.c
src/acvp_cmac.c
src/acvp_des.c
src/acvp_dsa.c
src/acvp_hash.c
src/acvp_kdf135_snmp.c
src/acvp_kdf135_ssh.c
src/acvp_lcl.h
src/acvp_rsa.c
src/acvp_util.c

- Addresses memory leaks from libacvp
- Fixes static analysis errors
- Fixes build warnings

Addresses valgrind and coverity issues

---

src/acvp.h

Adds doxygen documentation for remaining public API methods

Adds doxygen comments for remaining API methods

---

src/acvp.c
src/acvp.h
src/acvp_aes.c
src/acvp_cmac.c
src/acvp_des.c
src/acvp_drbg.c
src/acvp_dsa.c
src/acvp_hash.c
src/acvp_hmac.c
src/acvp_kdf135_snmp.c
src/acvp_kdf135_ssh.c
src/acvp_kdf135_tls.c
src/acvp_lcl.h
src/acvp_rsa.c
src/acvp_transport.c
src/acvp_util.c

- Converts all tabs to spaces
- Fixes indentation
- Adds curly braces to single statement control flows

Adds changes from code style script

---

app/app_main.c
src/acvp.c
src/acvp.h
src/acvp_lcl.h

- Handles different field names in AES for now
- Updates CMAC keyLen and keyingOption properties for updated spec
- Puts alg registrations into their own methods for readability

Interop json fields

---

app/app_main.c
src/acvp.c
src/acvp.h
src/acvp_cmac.c

- Adds proper support for CMAC-TDES
- Adjusts byte/string mismatches

Updates for CMAC interop

---

app/app_main.c
src/acvp.c
src/acvp_cmac.c
src/acvp_lcl.h
src/acvp_util.c

- Improvements made after testing

Adds a few cleanup items after merging CMAC interop

---

app/app_main.c
src/acvp.c
src/acvp_cmac.c
src/acvp_drbg.c

Adjustments to JSON registration and JSON test-case output

---

app/app_main.c
src/acvp.c
src/acvp.h
src/acvp_aes.c
src/acvp_des.c
src/acvp_lcl.h

Pull in changes already committed to our internal bitbucket

Add XTS, KWP and CTR modes

---

app/app_main.c
src/acvp.h
src/acvp_lcl.h
src/acvp_util.c

- removes a #define for the mod values
- cleans up unused #defines 
- updates valid values for strings based on bitlens in specs

Cleans up attribute values and usages

---

src/acvp_ecdsa.c
src/acvp_lcl.h
src/acvp_rsa_keygen.c
src/acvp_rsa_sig.c

So that the library code passes the test cases to the proper application handler

Updates mode strings to be unique

---

Makefile
Makefile.fom
Makefile.murl
Makefile.win
app/app_main.c
src/acvp.c
src/acvp.h
src/acvp_kdf135_srtp.c
src/acvp_lcl.h

Adds library support for KDF135 SRTP
Interop testing to come...

Kdf135 srtp

---

app/app_lcl.h
app/app_main.c
src/acvp.c
src/acvp.h
src/acvp_dsa.c
src/acvp_lcl.h

Interop complete for SigGen, KeyGen and SigVer

KAT processing for DSA PQGGEN, SIGGEN and SIGVER.  Plus interop for SigGen, KeyGen and SigVer

---

Makefile
Makefile.fom
Makefile.murl
Makefile.win
app/app_main.c
src/acvp.c
src/acvp.h
src/acvp_kdf135_x963.c
src/acvp_lcl.h

- Does not include example application test processing
- Does not include updates from interop testing

Kdf135 x963

---

app/app_main.c
src/acvp.c
src/acvp.h
src/acvp_kdf135_snmp.c
src/acvp_lcl.h

- Adds the rest of the parameters to the KDF SNMP registration code
- Updates strings from updated JSON specs

Kdf snmp library support

---

src/acvp.c
src/acvp_lcl.h
src/acvp_transport.c

Also made results request endless since we now have a refresh on the password.

Add TOTP password refresh in response to HTTP 401

---

src/acvp.c
src/acvp_capabilities.c
src/acvp_kas_ecc.c
src/acvp_kas_ffc.c

I just noticed that my last few pull requests used tabs instead of spaces as is the style for libacvp. My bad :P Here is the fix.

Fix Style: replace tabs with spaces

---

app/app_main.c
src/acvp_build_register.c
src/acvp_cmac.c

Also a couple of minor fixes/additions

Matching algorithm sheet with capabilities

---

src/acvp_lcl.h

Updates version string

---

src/acvp.h
src/acvp_build_register.c
src/acvp_capabilities.c
src/acvp_dsa.c
src/acvp_kas_ecc.c

Fix kdf135_tls enable cap with sha

---

app/app_main.c
src/acvp.h
src/acvp_aes.c
src/acvp_cmac.c
src/acvp_des.c
src/acvp_dsa.c
src/acvp_hmac.c
src/acvp_kas_ecc.c
src/acvp_kas_ffc.c
src/acvp_kdf108.c
src/acvp_kdf135_ikev1.c
src/acvp_kdf135_ikev2.c
src/acvp_kdf135_snmp.c
src/acvp_kdf135_srtp.c
src/acvp_kdf135_ssh.c
src/acvp_kdf135_tls.c
src/acvp_kdf135_x963.c

* Changed cmac_tc to use integer flas instead of char*

Always free test_case heap in module if error

---

src/acvp.c
src/acvp_build_register.c
src/acvp_kdf135_snmp.c
src/acvp_lcl.h
src/acvp_util.c

Made user stories for failure path in library and app code.

Address leaks in success path in the library

---

src/acvp.c

And I corrected the error messages on the login/login response failure - please look at that to be sure I didn't mess that up :)

final results display broken by leak fixes

---

src/acvp_aes.c
src/acvp_lcl.h
src/acvp_util.c

 fix AES json leaks and add common free function

---

src/acvp_des.c
src/acvp_kdf108.c
src/acvp_kdf135_ikev1.c
src/acvp_kdf135_ikev2.c
src/acvp_kdf135_snmp.c
src/acvp_kdf135_srtp.c
src/acvp_kdf135_ssh.c
src/acvp_kdf135_tls.c
src/acvp_kdf135_x963.c

more library leaks, tdes and kdfs

---

src/acvp.c
src/acvp_build_register.c

from UT of acvp.c acvp_util.c acvp_capabilities.c acvp_build_register.c

more leak fixes

---

src/acvp_transport.c

Also synced the http user-agent changes (libacvp/VERSION)

Fix transport error message check

---

src/acvp_kas_ffc.c

test_type was getting zeroed between test cases resulting in a crash in the app code.

fix kas-ffc crash

---

include/acvp/acvp_lcl.h
src/acvp.c
src/acvp_build_register.c
src/acvp_transport.c

The other algorithms need "revision" field added.

Support acvp 1.0 (hash only)

---

app/app_cli.c
app/app_drbg.c
app/app_main.c
include/acvp/acvp.h
src/acvp_build_register.c
src/acvp_capabilities.c
test/test_acvp.c
test/test_acvp_build_register.c
test/test_acvp_capabilities.c
test/test_acvp_drbg.c

no longer need the drbg-specific prereq code
fixed the CLI bug from today
updated the UT for DRBG
couple of other minor bugs

DRBG can now support multiple sub-modes per mode

---

src/acvp.c
src/acvp_transport.c

more in the internal repo after these are merged in

Coverity fixes

---

app/app_main.c
include/acvp/acvp.h
src/acvp.c

and fix a leak triggered by retries

Utilize the new PUT flow for alg cert request in offline mode

---

app/app_aes.c
app/app_main.c
include/acvp/acvp.h
include/acvp/acvp_lcl.h
src/acvp.c
src/acvp_aes.c
src/acvp_build_register.c
src/acvp_capabilities.c

- Integrated AES-GMAC support into library, basically AES-GCM with pt/ct length of 0
- Added AES-GMAC registration and handling into sample application

Integrated AES-GMAC support into the library and sample app

---

app/app_fips_init_lcl.h
app/app_kas.c
configure
configure.ac
murl/Makefile
murl/README
murl/murl.c
src/acvp_transport.c
src/acvp_util.c

This will get external working and then there will work on internal as well

Get murl working for 1.0.2 and 1.1.1

---

docker/README.md

Update README.md for docker instructions

---

src/acvp.c

Fixed memory issues with recent implementation. I am greatly sorry for any inconvenience.

Fixed issues with reporting failed algorithms

---

README.md
app/app_aes.c
metadata/creation.json
metadata/validation.json
metadata/vendor.json
src/acvp.c
src/acvp_dsa.c
src/acvp_kdf108.c
src/acvp_transport.c
src/acvp_util.c
test/test_acvp.c
test/test_acvp_dsa.c
test/test_acvp_transport.c
test/test_acvp_utils.c
test/test_app_aes.c
test/test_app_cmac.c
test/test_app_hmac.c

-Updated curl_easy_setopt calls to check return values, as requested by newer coverity verison.
-Fixed issue with MCT testing and freeing.
- Update copyright year in files modified this year.
-Minor readme updates (more to come).
-Misc fixes/changes

Updated readme, misc fixes

---

include/acvp/acvp.h
src/acvp.c

Last of logging changes for now (and hopefully of PRs for the day)

More logging improvements, made version formatting change in header file

---

test/test_app_ecdsa.c

Fixing crashes that did not appear locally when testing.

More memory fixes :(

---

src/acvp.c

already fixed internally for sake of speed

bugfix for null CTX

---

src/acvp.c
src/acvp_util.c

Unless errors or bugs pop up, probable final changes before initial release.

Improved logging, fixed lost memory blocks, removed ancient comments

---

src/acvp_transport.c

temporarily Fixed, but function needs lots of work done to it as a whole

Moved param initialization back outside for loop

---

src/acvp.c

Refresh token for get_results

---

app/app_des.c
test/Makefile.am
test/Makefile.in
test/test_app_aes.c
test/test_app_des.c

Added UTs for acvp_app TDES. Made small changes to memory freeing in app DES code.

acvp_app DES UTs, some small changes to app_des

---

README.md

To view properly go to
https://github.com/bfussell/libacvp/

Update README with note about changes and full algorithm support table

---

include/acvp/acvp.h
metadata/validation.json
src/acvp_operating_env.c
test/test_acvp_operating_env.c

Seems to work with old metadata and metadata with vendor_id and id removed.

remove id/vendor_id from metadata, track with local index

---

src/acvp_operating_env.c

Tested as much as possible within a short time frame and with other issues on NIST server currently
Known issues: possible errors with edge cases regarding validation metadata

Updating vendor metadata processing

---

src/acvp_operating_env.c

Will be looking through all of this code more over time.

Added null checks for strdup

---

app/app_main.c

 remove duplicate registration options

---

src/acvp_transport.c

Should investigate if there is a better way to handle this scenario in the future, or maybe if a expired JWT message should be added to the spec.
Tested by setting retry values to 30 minutes, hence the delay in getting this in.

Updated refresh check

---

app/app_fips_lcl.h
app/app_rsa.c

Found in the pipeline and by Polaris(not seen in pipeline)

Fix a few build warnings

---

Makefile.am
Makefile.in
README.md
app/app_main.c
src/acvp_build_register.c

Also removed empty payloadLen object for AES-GMAC capabilities registration

Fixes for make dist and other small change (1.1.0)

---

src/acvp_transport.c

Checks for HTTP code upon uploading vector set - if response is 400 (bad request), perform a PUT instead of a POST which enables re-uploading.

Support Vector Set Reupload

---

include/acvp/acvp_lcl.h
src/acvp.c
src/acvp_transport.c
test/test_acvp_transport.c

56Cr1 updates still incoming ASAP. Having some issues with registration as the spec is rather unclear on a few things.

Removed server/getenv from transport tests, updated user-agent calls to be cleaner

---

src/acvp_transport.c

Simply moved all the user agent code to the bottom of acvp_transport.c to keep it out of the way/out of the ifndef acvp_offline blocks, and added a check to return immediately if in offline mode. Apologies for not catching this initially. (Not sure why the diff got so messy).

Fixes user agent for offline

---

README.md
app/app_cli.c
app/app_fips_lcl.h
app/app_kas.c
app/app_lcl.h
app/app_main.c
include/acvp/acvp.h
include/acvp/acvp_lcl.h
ms/resources/Source.def
src/Makefile.am
src/Makefile.in
src/acvp.c
src/acvp_build_register.c
src/acvp_capabilities.c
src/acvp_kas_ffc.c
src/acvp_kas_ifc.c

First commit of KAS-IFC-SSC

---

src/acvp_kdf135_snmp.c

p_len changed from bytes to bits as per https://github.com/usnistgov/ACVP/issues/1051

Fixing len for snmp

---

test/json/kdf135_snmp/kdf135_snmp1.json
test/json/kdf135_snmp/kdf135_snmp11.json
test/json/kdf135_snmp/kdf135_snmp12.json
test/json/kdf135_snmp/kdf135_snmp4.json

These have already been merged internally to speed up pipeline

Fixing tests for snmp

---

app/app_kas_kdf.c
src/acvp_kas_kdf.c

Forgot to include the most important kas_kdf src files in yesterday's PR.

Added missing acvp_kas_kdf.c and app_kas_kdf.c files.

---

app/app_kas_kdf.c
app/app_lcl.h
app/app_main.c
app/app_utils.c
include/acvp/acvp.h
src/acvp_build_register.c
src/acvp_kas_kdf.c
src/acvp_util.c

Resolving conflicts momentarily.

App implementation for HKDF and onestep kdf, some fixes

---

app/app_cli.c
app/app_fips_lcl.h
app/app_kas.c
app/app_lcl.h
app/app_main.c
include/acvp/acvp.h
include/acvp/acvp_lcl.h
src/Makefile.am
src/Makefile.in
src/acvp.c
src/acvp_build_register.c
src/acvp_capabilities.c
src/acvp_safe_primes.c

Add testing for safe primes

---

src/acvp_kdf_tls13.c

Fixed length check issue with TLS 1.3 kdf

---

app/app_main.c
src/acvp_capabilities.c

Remove DRBG as possible pbkdf prereq and ensure app uses hmac as prereq

---

test/test_acvp_operating_env.c

Not quite sure how I didn't get this error on my platform.

Fixed function call in test cases

---

Makefile.am
Makefile.in

Doxyfile missing from make dist. Likely will respin the release; not the most urgent issue to fix.

Fixed adding doxyfile to dist

---

ms/make_app.bat
ms/make_lib.bat
src/acvp.c

Batch is notoriously picky; a few updates that should help build edge cases on the windows side.
PUT requests now respond with output

Windows script format updates, PUT request updates

---

configure
configure.ac

Made a bit of a mess of this check. Thanks!

Another build system fix

---

src/acvp_build_register.c

For current code, already fixed in TBD code. To close #694

Fix for KAS2 Registration

---

include/acvp/acvp_lcl.h
src/acvp_capabilities.c
src/acvp_util.c

Cleanup acvp_capabilities list code (1_TBD)

---

app/app_ecdsa.c
app/app_kas.c
app/app_kda.c
app/app_kdf.c
app/app_rsa.c
src/acvp_capabilities.c
src/acvp_kas_ifc.c

Fixes from comments, coverity, and safeC

Misc. formatting and check fixes for 3.0 support branch

---

app/app_kda.c
app/app_main.c

Use HKDF for twostep instead of MAC then KBKDF to match OpenSSL cert

Update twostep implementation to match OpenSSL

---

app/Makefile.am
app/Makefile.in
app/app_cli.c
app/app_lcl.h
app/app_lms.c
app/app_main.c
include/acvp/acvp.h
include/acvp/acvp_lcl.h
ms/resources/Source.def
src/Makefile.am
src/Makefile.in
src/acvp.c
src/acvp_build_register.c
src/acvp_capabilities.c
src/acvp_lms.c
src/acvp_util.c

UTs will come at a later date.
App handler includes comment describing outputs.

Add support for LMS to library

---

app/app_drbg.c
app/app_ecdsa.c
app/app_kas.c
src/acvp_util.c
test/test_acvp_kas_ifc.c
test/test_app_drbg.c
test/test_app_ecdsa.c
test/test_app_kas_ecc.c
test/test_app_kas_ffc.c
test/test_app_rsa_keygen.c
test/test_app_safe_primes.c

Updates for KAS-IFC UTs still in progress; those are a bit messy.

Misc. fix for UTs for libacvp 2.0, LMS fix, copyright years

---

src/acvp.c
src/acvp_rsa_sig.c
src/acvp_transport.c

Remove areas of NULL/0 setting vars when they will not be used in that state again

static analysis fixes for 1.5.X

---

.gitignore
app/app_kas.c
test/test_acvp_utils.c
test/test_app_kas_ifc.c

Add some more files/folders to gitignore, add a check to remove junk files created by UTs, update app KAS-IFC UTs for new test structure.

Update KAS-IFC UTs for new tc structure, misc. other fixes

---

app/Makefile.am
app/Makefile.in
app/app_cli.c
app/app_ecdsa.c
app/app_eddsa.c
app/app_lcl.h
app/app_main.c
app/app_utils.c
include/acvp/acvp.h
include/acvp/acvp_lcl.h
src/Makefile.am
src/Makefile.in
src/acvp.c
src/acvp_build_register.c
src/acvp_capabilities.c
src/acvp_eddsa.c
src/acvp_util.c

App and library support for EDDSA. UTs not yet completed. Also fix an RSA registration change.
Waiting for details on EDDSA KeyVer implementation for app.

Support for EDDSA in library and app

---

test/test_acvp.c
test/test_acvp_capabilities.c
test/ut_common.h

Adjust for new max filename length, and new max AES param lengths

Fixes for some UTs

---

app/implementations/openssl/3/iut_kas.c
app/implementations/openssl/3/iut_kdf.c
test/Makefile.am
test/Makefile.in
test/implementations/openssl/3/test_iut_aes.c
test/implementations/openssl/3/test_iut_cmac.c
test/implementations/openssl/3/test_iut_des.c
test/implementations/openssl/3/test_iut_drbg.c
test/implementations/openssl/3/test_iut_ecdsa.c
test/implementations/openssl/3/test_iut_hash.c
test/implementations/openssl/3/test_iut_hmac.c
test/implementations/openssl/3/test_iut_kas_ecc.c
test/implementations/openssl/3/test_iut_kas_ffc.c
test/implementations/openssl/3/test_iut_kdf108.c
test/implementations/openssl/3/test_iut_kdf135_ssh.c
test/implementations/openssl/3/test_iut_kdf_tls12.c
test/implementations/openssl/3/test_iut_kdf_tls13.c
test/implementations/openssl/3/test_iut_kmac.c
test/implementations/openssl/3/test_iut_kts_ifc.c
test/implementations/openssl/3/test_iut_pbkdf.c
test/implementations/openssl/3/test_iut_rsa_keygen.c
test/implementations/openssl/3/test_iut_rsa_sig.c
test/implementations/openssl/3/test_iut_safe_primes.c

- Add KDF app UTs
- Add KTS-IFC app UTs
- Remove ACVP CTX reference from other app UTs - these CTX aren't even initialized and we were trying to log to them in failures
- Update KDF and KTS handler code with some checks for UTs

Add KDF app UTs, updates to other app UTs

---

.gitignore
app/app_main.c
src/acvp.c

As requested on #866, I have rebased on top of libacvp_2_1_0-throttle and target that branch

Fix ECDSA in FIPS 186-5 

---

app/app_ecdsa.c
app/app_main.c
src/acvp_build_register.c
src/acvp_capabilities.c

Should be the last commit before releasing 2.1.2.

Remove component testing from ECDSA sigver

---

app/app_cli.c
app/app_main.c
app/implementations/README.md
app/implementations/jitter_entropy/README.md
app/implementations/liboqs/README.md
app/implementations/openssl/README.md
app/implementations/stubs/README.md
configure
configure.ac
test/Makefile.am
test/Makefile.in

- **Add READMEs briefly describing each test harness**
- Fix curl linking issues for some online/offline builds
- Fix return value checks in various places in the main application flow; return 0 on version command (will require further testing before release)
- Fix application wrapper code for new registration calls

Build system fixes, README additions, return value fixes
