cisco/libacvp

- src/acvp.c
- src/acvp_aes.c
- src/acvp_des.c
- src/acvp_drbg.c
- src/acvp_hash.c
- src/acvp_lcl.h
- src/acvp_util.c
These changes ensures that the version (sent in a preamble) is always the first in the array.
> Update for ordered fields using an array.

- app/app_main.c
- src/acvp.c
- src/acvp.h
- src/acvp_aes.c
- src/acvp_des.c
- src/acvp_drbg.c
- src/acvp_hash.c
- src/acvp_hmac.c
- src/acvp_lcl.h
- src/acvp_transport.c
- src/acvp_util.c
This PR has 3 functional changes. Changed the logging so it can be level controlled via command line argument.  Added prerequisites for AES-GCM and AES-CCM.  Added parameter capabilities for SHA.
> Add log levels, prereq for AEAD ciphers and SHA parms set

- src/acvp_aes.c
- src/acvp_cmac.c
- src/acvp_des.c
- src/acvp_drbg.c
- src/acvp_hash.c
- src/acvp_hmac.c
Sorry for the noise, my editor converts tabs to spaces... maybe there is an ignore whitespace option on github like there is on bitbucket?
The actual fix is around the call to json_serialize_to_string_pretty in each acvp_*.c file
> Fixes memory resulting from json library method call

- app/app_main.c
- src/acvp.h
- src/acvp_hmac.c
- src/acvp_lcl.h
If msglen isn't included in the server response, the msglen will be set in the kat handler.
This PR also renames a few variables to be consistent with HMAC.
> Hmac msglen fix

- app/app_main.c
- src/acvp_lcl.h
Update “HMAC-SHA1” to match spec with “HMAC-SHA-1”.
Registered Key ranges to use values below and above the block size.
> HMAC SHA1 name did not match spec

- app/app_main.c
- src/acvp.c
- src/acvp.h
- src/acvp_lcl.h
Collapses repeated prereq code into common structs and methods
DRBG prereqs are not included in this because the prereqs for DRBG are added according to each mode and therefore exist at a different level
> Common prereq

- app/app_main.c
KDFs were missed in prereg refactoring since they were commented out
> prereq changes for KDFs

- app/app_main.c
- src/acvp.c
- src/acvp.h
- src/acvp_lcl.h
- src/acvp_util.c
app_main has a fair amount of whitespace changes (sorry... I should really check the settings on my editor so it doesn't do this to you guys every time), but here is an outline of the rest so you don't have to dig:
- RSA API was consolidated because of the new "hashPair" object structure in the JSON registration. Because of this, there are a handful of API calls that have a NULL/0 final variable
- new structure added for "hashPair" and "salt" object was removed as it is now unnecessary
- removed a good amount of searching logic that was being called but not actually used
- reorganizing the JSON output
- added a registration for CMAC_TDES
--> there is one more layer of abstraction that I would like to add so that multiple RSA handlers can be registered in the case of multiples modes being …
> Spec updates

- README.md
- app/app_main.c
- src/acvp_rsa_keygen.c
Adds comments where internal API calls were indicating that crypto module API will need to be filled in
> Removes internal crypto module API in example client 

- Makefile
- Makefile.fom
- Makefile.murl
- Makefile.win
- app/app_main.c
- src/acvp.c
- src/acvp.h
- src/acvp_kdf135_snmp.c
- src/acvp_kdf135_tpm.c
- src/acvp_lcl.h
- Library support to add kdf tpm to registration
- This does not include interop
**TPM (and a couple of other TPMs) spec's aren't up to date, so I haven't fixed JSON naming, etc in the registration since the consistency is still to be addressed :)
> Kdf135 tpm

- app/app_main.c
- src/acvp.c
- src/acvp.h
- src/acvp_kas_ecc.c
- src/acvp_lcl.h
Plus fixed a bug in TOTP password generation when there was a NULL in the string which caused the key length to be wrong.
> KAS-ECC Component mode and some info for non-Component mode

- app/app_main.c
- src/acvp.h
- src/acvp_build_register.c
- src/acvp_transport.c
- src/acvp_util.c
Fixed crash in transport when to json passed to send functions
Enable all 3 drbg in no-runtime builds
aes keywrap on by default
move pre-req value outside of enable functions because it was on the stack and could get corrupted
>  Various Updates, see description

- src/acvp_kas_ecc.c
- src/acvp_kas_ffc.c
This pull request adds null checks for several cases in which bad JSON input could cause a null dereference and program crash.
--
> Add error handling for bad JSON in acvp_kas files

- src/acvp_capabilities.c
This pull request fixes a variety of related memory leaks which can be caused by memory being allocated and then passed to another function which may have a failure before storing the pointer in the context.
--
> Fix memory leaks in acvp_capabilities

- src/acvp.c
This pull request prevents a null value being dereferenced and a possible program crash by adding a check after a call to malloc().
--
> Prevent Null Dereference in acvp.c

- src/acvp.c
This pull request prevents an uninitialized return value in "acvp_check_test_results" in the case that the context contains no vector sets, hopefully preventing confusing error messages.
--
> Prevent uninitialized return value in acvp.c

- src/acvp.c
This pull request prevents an uninitialized return value in "acvp_process_tests" in the case that the context contains no vector sets, hopefully preventing confusing error messages.
--
> Prevent 2nd uninitialized return value in acvp.c

- src/acvp_kdf135_ikev1.c
Now the length check accounts for extra bits that don't form a full
byte.
> Fix kdf135_ikev1 init/resp_nonce length check

- src/acvp.c
Can cause a segfault, at least it does on my server.
> NULL sample_buf to prevent re-use after free

- src/acvp_des.c
This works today, but I opened an issue on the ACVP github because AES and TDES operate a bit differently. Will wait on AES until after I get that issue resolved.
> Interop with DES CFB1

- app/app_main.c
- src/acvp.h
- src/acvp_aes.c
- src/acvp_des.c
Note that DSA PQGVER will still not pass due to issue #509 and #494 so further testing will be required once NIST fixes those.
> Port CTR changes to external and PQGVER interoperability fix

- .muse/config
- .muse/setup.sh
libacvp folks,
This patch adds minor configuration and setup files which aid automated analysis of libacvp code.  These files are in a hidden directory, unneeded by any part of the project or normal build system, and thought to be sufficiently uninteresting so that normal development can proceed as though they don't exist.  I'm happy to address any issues.
As in the past, the analyzer is there to find issues such as memory leaks, dead stores, and pointer exceptions.
In more detail:
In the past libacvp had a committed a `Makefile` which was automatically detected.  Modern libacvp branches include both a build.gradle and autotools (configure) with an assumption of gcc when on linux. With these changes the analyzer's current auto-detection of the build system is not sufficiently smart.  The …
> Add a configuration to aid analysis

- app/app_cli.c
- app/app_lcl.h
- app/app_main.c
- app/app_utils.c
- src/acvp.c
- src/acvp_transport.c
- Don't require mutual-authentication.
- Don't require a custom CA file (will use system store as default)
- Don't require 2fa
- Sets the default path segment
> Remove defaults for ca, client cert/key, and set default for path_seg

- src/acvp_transport.c
Those that use path_segment need the / when building the URI, these that were changed do not.
> remove extra / on some URI strings

- app/app_main.c
- scripts/nist_setup.bat
- scripts/nist_setup.sh
- src/acvp_rsa_sig.c
This is merely a single workaround for a bigger problem documented as an issue on the ACVP github.
If they don't fix it and there are other instances, we will need to create a common utility to pad strings when they are not fully qualified.
> Re-enable SigGen and address missing 00 at start of signature

- app/app_cli.c
- app/app_lcl.h
- app/app_main.c
- include/acvp/acvp.h
- include/acvp/acvp_lcl.h
- metadata/person.json
- metadata/vendor.json
- src/acvp.c
- src/acvp_transport.c
added metadata examples that can be used with POST
Will need to add some README updates with metadata format and examples such as:
app/.libs/acvp_app --all_algs  --get '/acvp/v1/vendors?vendorId[0]=lt:20' --verbose
app/.libs/acvp_app --all_algs --get '/acvp/v1/vendors?name[0]=contains:acme' --verbose
app/.libs/acvp_app --all_algs  --post person.json --verbose
app/.libs/acvp_app --all_algs  --post vendor.json --verbose
> Make status request a generic GET and add generic POST commands

- app/app_cli.c
- app/app_lcl.h
- app/app_main.c
- include/acvp/acvp.h
- include/acvp/acvp_lcl.h
- metadata/module.json
- metadata/oe.json
- metadata/person.json
- metadata/vendor.json
- src/acvp.c
- src/acvp_transport.c
Deprecated large URL support
Test runs now create a json file that has the JWT and testSession URL that can be used for validation PUTs
Added --put command line option for:
validation request PUT
metadata modification PUT
> --put, deprecate large, save JWT and testSession ID

- include/acvp/acvp_lcl.h
- src/acvp.c
- All instances of waiting for server to create or process vector sets now have a maximum wait time (1 hour for now)
- There is now a retry backoff for waiting for the server to complete processing at vector sets (starts at 30 seconds, doubles until it reaches max of 5 minutes, easy to change as needed)
- Tested w/ NIST server by using arbitrarily low retry and max wait times
- Note: There is no retry backoff for waiting on the server to CREATE vector sets currently, as that retry time is provided by the server as per the spec
- Note: Fixed bug where error return values from acvp_process_vsid would not be handled properly if acvp_json_serialize_to_file_pretty_a (called afterwards) had no errors
- Note: todo: create sample app solution for reconnecting and retrieving vector set results at …
> Server Request Retry Backoff

- app/app_cli.c
- app/app_lcl.h
- app/app_main.c
- include/acvp/acvp.h
- src/acvp.c
- test/json/getResults.json
- test/test_acvp.c
- acvp_app now has an argument for --get_results <file>, where file is a json file containing the session URL and JWT.
- New API function acvp_get_results_from_server which takes a CTX and filename as parameters
- This can be used to retrieve results from previous sessions, including ones where the client timed out or lost connection while waiting for the server to finish processing
- Created tests
- Tested with 1.1.1; closed the process while server was returning "incomplete" messages and requesting retries, and successfully reconnected and obtained results
- Made vector_upload argument no longer require an argument for an algorithm suite (unused)
> New CL argument for acvp_app: --get_results <file>

- app/app_aes.c
- app/app_cmac.c
- app/app_des.c
- app/app_fips_lcl.h
- app/app_hmac.c
- app/app_kas.c
- app/app_kdf.c
- app/app_main.c
- app/app_sha.c
Somewhere during the restructuring of the app code we stopped using fipssyms.h to map calls directly to the FOM. AES and TDES required changes to the functions they used, but others just needed to include the header files to remap.  Also don't seem to need FIPS_mode_set(1) for drbg, works without it.
> Repair app code so it uses FOM directly

- build.gradle
- include/acvp/acvp_lcl.h
- safe_c_stub/include/safe_str_lib.h
- safe_c_stub/src/safe_str_stub.c
- src/acvp.c
- src/acvp_transport.c
The HTTP User-agent now consists of: 
Library name/version; OS name; os/kernel version; processor architecture; processor name; compiler/version.
On Linux, Windows, and Mac OS on x86 or x64 platforms, this is all automatically populated. In other situations, depending on the environment, some of this information may be populated. For any information that cannot be found, an environment variable can be defined (undefined variables for info not automatically detected by the library throw a warning but do not prevent user from continuing).
Tested on Ubuntu, Windows 10, and Mac OS.
The Safe C Stub now contains function strremovews_s, which allows for leading and trailing white space on strings to be safely removed.
> HTTP User-Agent Upgrade

- app/app_cmac.c
- app/app_main.c
- scripts/nist_setup.bat
- scripts/nist_setup.sh
- src/acvp_transport.c
1. CMAC: Can't pass size_t back from FOM into an int.
2. GCM: Not all FOM implementatoins support 96 bit tag len
3. Scripts: point out the user generates the key, not NIST
4. VS Results should be fully printed at a STATUS level or higher.
> minor cleanup found during cross compiles

- app/app_fips_init_lcl.h
- app/app_fips_lcl.h
- app/app_hmac.c
- app/app_main.c
- app/app_sha.c
- src/acvp.c
- src/acvp_aes.c
- src/acvp_build_register.c
- src/acvp_capabilities.c
- src/acvp_transport.c
All HMAC_SHA3 algorithms now register fully with the library. All HMAC_SHA3 registrations are now enabled in the sample app if a high enough openSSL version is used.
Many tab characters were scattered throughout several source files in random places. These have been replaced with spaces (Note: external header files with tabs and makefiles are not adjusted)
AES-GCM-SIV now handles its static ivLen and tagLen values in accordance with the spec clarification - if the server JSON provides those values, it uses and checks them, otherwise it just uses the static 96 and 128 values the algorithm requires. 
Added a few words of clarification to an error or two.
> Sha3 hmac registration, Removed many tab characters, adjusted AES-GCM-SIV, small other changes

- app/app_aes.c
- include/acvp/acvp_lcl.h
- src/acvp.c
- src/acvp_transport.c
- src/acvp_util.c
NOTE: large diff
- libacvp now logs failed algorithm names when reporting results (prevoiously only reported failed vector set URLs).
- Many server responses were moved from default "status" logging into --info. This will make regular run logs much shorter (and easier to read). 
- Detailed failure responses moved to --verbose (Does not give useful information unless user manually searches for which test group that test case ID is in)
- added acvp_append_str_list and acvp_lookup_str_list to make handling ACVP_STRING_LISTs easier
- Removed some redundant logging, reorganized some code for cleanliness
Todo: add CLI arguments to retrieve vector sets from a previous test session, and detailed fails from a previous test session, so people can debug individual test cases if desired.
> Failed Algorithm Reporting, Logging Changes

- src/acvp.c
Remove integer declaration from for loop to make it more compatible with C standards
> Fixing loop declaration bug

- src/acvp.c
- src/acvp_util.c
used strnlen for calloc, and did not for the strncpy. This has been fixed. 
Also had rewritten acvp_append_str_list when debugging, and the new version is cleaner, so including this. 
Will be much more careful with bounds creation and checking in the future.
> Fix memory corruption issue with results reporting

- src/acvp.c
- src/acvp_kdf108.c
- test/test_acvp.c
- test/test_acvp_transport.c
- test/test_acvp_utils.c
- test/test_app_cmac.c
- test/test_app_hmac.c
Added extra space in buffer for TOTP null, and fixed freeing memory in some error cases for kdf108. Freed memory in a bunch of test cases. All IDed using valgrind with the test suite - more testing needs to be done on app.
> Some Memory Fixes (Mostly Tests)

- build.gradle
- include/acvp/acvp_lcl.h
- src/acvp.c
Changed output executable to be named acvp_app instead of example.
Updated windows Sleep call to wait the correct amount of time.
Added a switch to ignore a gnuc specific __attribute__.
> Bugfixes for windows

- app/app_main.c
Added a friendly reminder to set server (And additionally to read the --help output) if the ACV server is not set.
Requested internally.
> Added warning to set env variables

- app/app_aes.c
- test/Makefile.am
- test/Makefile.in
- test/test_app_aes.c
**please review carefully, as I want to make sure the tests cover the desired criteria, thanks!**
-Added failure tests to app_aes_handler, app_aes_keywrap_handler, and app_aes_handler_aead
-This includes some tests where the crypto library gets wrong lengths etc, to ensure the app has no issues - the acvp library/server is responsible for validating input/response.
-Fixed still reachable blocks in the app code for error conditions
-Added printfs to some places in app code for error conditions
-Updated the needed makefiles (Please review to ensure done correctly)
> Added UTs for app_aes functions. Fixed leaks in acvp_aes_handler.

- app/app_aes.c
- app/app_main.c
- include/acvp/acvp_lcl.h
- src/acvp.c
- src/acvp_aes.c
- src/acvp_cmac.c
- src/acvp_des.c
- src/acvp_drbg.c
- src/acvp_dsa.c
- src/acvp_ecdsa.c
- src/acvp_hash.c
- src/acvp_hmac.c
- src/acvp_kas_ecc.c
- src/acvp_kas_ffc.c
- src/acvp_kdf108.c
- src/acvp_kdf135_ikev1.c
- src/acvp_kdf135_ikev2.c
- src/acvp_kdf135_snmp.c
- src/acvp_kdf135_srtp.c
- src/acvp_kdf135_ssh.c
- src/acvp_kdf135_tls.c
- src/acvp_kdf135_x963.c
- src/acvp_operating_env.c
- src/acvp_rsa_keygen.c
- src/acvp_rsa_sig.c
- src/acvp_transport.c
-Moved lots of status logging into info logging - mostly network action logging.
-Moved lots of info logging into verbose logging - mostly details of test cases.
-Got rid of some verbose logging - specifically all logging of MCT iterations - just too many lines.
-Removed logging of tokens/any auth bearers regardless of verbosity level.
-Added some logging into status to make flow more easy to understand to end users.
> Substantial logging changes

- app/app_aes.c
- src/acvp.c
- test/test_app_aes.c
- test/test_app_ecdsa.c
- test/test_app_kas_ecc.c
- test/test_app_kas_ffc.c
- test/test_app_rsa_keygen.c
- test/test_app_rsa_sig.c
Adding frees to still reachable blocks in test cases - objective is to ensure issues reported by valgrind are relevant to the actual software and not TCs as we update pipeline internally soon.
Removed retry backoff.
> Memory releases in test cases, removed retry backoff

- test/test_app_ecdsa.c
The app ECDSA test file is structured differently than the other test cases and I did not look as closely (nor did they pop up in how I was building in OSS). Fixing a double free in certain cases.
> Fix double free in test case

- README.md
- src/acvp.c
- src/acvp_transport.c
POST and GET responses are now logged in default logging.
a 0 curl code (No response from server) now sends a more accurate message to the log.
The readme got a small FAQ section.
> Updated logging, updated readme

- app/app_cli.c
- app/app_lcl.h
- app/app_main.c
- include/acvp/acvp.h
- src/acvp.c
- test/test_acvp.c
--new API function acvp_resume_test_session
--Checks the results of a stored test session, finds vector set URLs with "unreceived" status, downloads those URLs, processes, and uploads
--new acvp_app argument, --resume_session <filename>
if --downloading vectors using --vector_req, it doesn't check status (nothing to check), just downloads all vector sets
Updated --vector_upload so it doesnt stop working if re-submitting a response, just skips instead
Added printf for verbose debugging that was missing
> Added resume session feature

- src/acvp_transport.c
Some faulty logic allowed writes past edge of buffer indefinitely.
(I had not altered or looked in-depth at this code previously)
Code will now just cut off any characters longer than the buffer instead of overflowing.
> Fixed buffer overflow issue in old code 

- src/acvp.c
Would result in NIST server returning with error if JWT had expired.
> Added JWT refresh to resume_session

- src/acvp.c
-Fixed double free if connectivity was lost while waiting to retry to get results
-Fixed potential double frees if json is malformed
> Fixed memory frees in some error situations

- app/app_cmac.c
Caused a crash due to stack corruption on certain targets
> Add a byte to key length to allow null termination

- .muse/setup.sh
LibSSL 1.0 isn't in Ubuntu 20.04, which is the new base image used by the MuseDev analysis system.
> Update to use libssl1.1 instead of 1.0

- app/app_main.c
- configure
- configure.ac
- test/Makefile.in
Fixes building with OpenSSL fom 2.0. must use --disable-kdf on the config line.
Note that AES-GMAC is currently failing several tests only for this FOM. Investigating.
> Added --disable-kdf for FOM without KDF support, added extern checks

- src/acvp.c
Was running login in acvp_run, which then called acvp_post_data, which called login again. Removed login call from acvp_post_data. Tested with posting sample vendor.json.
> Removed double login from --post operation

- app/app_cli.c
- app/app_lcl.h
- app/app_main.c
- src/acvp.c
- test/test_acvp.c
--json option for acvp_app changed to --manual_registration
acvp_set_json_filename can now only be used if acvp_mark_as_request_only has been used
Updated logic to properly run session with registration filename
> Updated some functionality around using registration files

- configure
- configure.ac
Allows for libacvp to be built, library only, without needing to specify --with-ssl-dir (or fom)
Does a check for libcurl any time --enable-offline is not set at configure step. Previously, if --with-libcurl-dir was not defined for a regular online build, you would get a vague "cannot find curl.h" error during make.
We now only set CC to fipsld in the case of building the static offline app, so library can be built without needing FOM dir in all other cases.
Large diff is mostly due to moving conditional sections around.
> Remove SLL/FOM check for --disable-app, added libcurl check to configure, only use fipsld when building app

- README.md
- app/app_cli.c
- include/acvp/acvp_lcl.h
- src/acvp.c
ACV_SESSION_SAVE_PATH can be used to define the location to save the file in. 
ACV_SESSION_SAVE_PREFIX can be used to define the prefix of the test session file. The default prefix remains "testSession". The format for the file will always be <prefix>_<ID number>.json.
In the case of an invalid path or prefix (or ones that are too long combined), we revert to the default setting - using testSession and whatever the OS decides for path (usually application directory).
In the case of valid path/prefix, but an error occurs while writing the file, the session will continue without writing a testSession file, but prints an error to the log. Usually would happen in case of folder not existing, or in case of not having write permissions to folder.
Given path and prefix may result in full file …
> Added ability to change path/prefix for session info file

- configure
- configure.ac
Fixing some pretty flawed logic checks from previous PR (x checks are more portable for very old shells that don't play well with empty vars)
> Fixing issues with value checks in configure.ac

- include/acvp/acvp.h
- include/acvp/acvp_lcl.h
- src/acvp.c
- src/acvp_aes.c
- src/acvp_cmac.c
- src/acvp_util.c
- Log messages that are now longer than the max allowed (currently 2048 chars) now get the end characters cut off in the log and replaced with a '...[truncated]\n' string. This is more communicative and the newline character makes logs cleaner.
- There is a new ACVP_LOG_NEWLINE macro which will send an empty string to the log callback. This is in a trend towards what I hope will be removing any and all printfs from the library itself for portability sake.
- TODO: Create a log function that get requests can use to print the curl buffer with no limit. Is sending a const pointer to the entire curl buffer to the application a risk if only done for --get requests?
- Beginning of reorganization of logging for vector sets, test groups, and test cases. Will be done in stages. This PR does it for …
> logging updates, formatting/logic fixes

- src/acvp.c
Quick fix for "error" test disposition while I polish the API and some surrounding API some more. Not certain what the NIST server will respond to request with in "error" case as unable to test.
> Fix for error check

- app/app_aes.c
- app/app_des.c
- include/acvp/acvp.h
- include/acvp/acvp_lcl.h
replacing MCT loop limits with references to MCT loop limits defined in headers (as per internal support case) so applications can reference them
> Moved MCT loop values to acvp.h so apps can use them

- ms/resources/Source.def
- src/acvp_rsa_sig.c
There does not seem to be any specific flag that differentiates legacy rsa vs regular, which is confusing because they have different sections in the spec, unless I am missing something. Regardless - adding support for the extra modulo and fixing a bug in the windows build process caused by forgetting to add the new API name to sources.def
> Adding more modulo support, fixing windows API issue

- README.md
- app/app_cli.c
- app/ketopt.h
Made a change to ketopt.h to enable use of optional arguments (It is already supposed to, but I think some previous adjustments may have broken it - unsure).
Some readme updates. Big updates to app_cli.c. If any arguments result in an error, the error is now printed after the help section is, so the user does not need to scroll up to see the errror.
Added support for different levels of verbosity in the --help section. using "acvp_app --help verbose" now results in more info being printed in the help section. This can and likely will be expanded upon later.
> Updated readme, help section 

- app/app_cli.c
- app/app_main.c
- include/acvp/acvp.h
- include/acvp/acvp_lcl.h
- ms/resources/Source.def
- src/acvp.c
- test/test_acvp.c
New API acvp_set_get_save_file for saving files when the session is marked as acvp_mark_as_get_only. App has been updated to use. So you can now do
./acvp_app --get /acvp/v1/etc --save_to filename.json
In next major release (probably a long time away), we would hope to add this as an optional parameter to acvp_mark_as_get_only instead of it being a separate API.
Increased curl buffer size to 32MB, and added comment blocks to enable_hmac and enable_cmac indicating the buffer size may need to be increased in some scenarios. 
Added UTs.
> New API acvp_set_get_save_file, curl buffer increase

- configure
- configure.ac
Fixes some issue with linking/library detection. Octeon SDK has multiple defines for libraries it looks at for conftest. Some platforms do not have libdl.a.
These only affect library detection and not the final build product - the linker flags for those are only controlled by the pre-existing envirionment before configure is called and the Makefile.am files (though configure sets vars that the makefiles can decide to use or not).
> Some fixes for android/octeon

- app/app_main.c
Updating OSS: Removing comment that says server doesnt support mod 4096. Adding mod4096 support for openSSL versions > 1.1.0 for offline testing (implies a custom crypto module is being used, and just assume it supports mod 4096)
> Update wording for mod 4096 support for rsa

- app/app_aes.c
- app/app_cmac.c
- app/app_des.c
- app/app_drbg.c
- app/app_ecdsa.c
- app/app_hmac.c
- app/app_main.c
- app/app_sha.c
- include/acvp/acvp.h
- include/acvp/acvp_lcl.h
- src/acvp.c
- src/acvp_aes.c
- src/acvp_build_register.c
- src/acvp_capabilities.c
- src/acvp_des.c
- src/acvp_kas_ecc.c
- src/acvp_kas_ffc.c
Tested with a sample session and zereod out results (got "fail" disposition but all fields and data were present)
Fixed small issue where negative value could be fed to some sym cipher parm API. Fortunately only caused an error from the server.
> Added library support for aes-xpn and disabled app registration

- .muse/config
- .muse/setup.sh
The muse config has lagged a bit with changes to both muse and libacvp.  This PR fixes the build system (which now requires a --with-libcurl-dir flag) and relaxes the configuration to allow all analyzers to run.
Analysis of this PR won't succeed because master analysis isn't currently functional.  The individual branch, however, [does work](https://console.muse.dev/result/TomMD/libacvp/01EQGYYVJCFMTPQGSHCM3Z9R6R?tab=results) so master will be in a good state post-merge.
> Update muse config

- app/app_kas.c
- test/test_acvp_kas_ifc.c
This may conflict since I already added it to internal, so I'll look out for merge conflict on the sync.
> Fix KAS-IFC leaks and remove unused function setup_fail

- app/app_kas.c
- app/app_kas_kdf.c
- app/ketopt.h
- ms/resources/Source.def
- ms/resources/acvp_app.vcxproj
- ms/resources/acvp_app.vcxproj.filters
- ms/resources/libacvp.vcxproj
- ms/resources/libacvp.vcxproj.filters
- safe_c_stub/src/safe_str_stub.c
- src/acvp_kas_kdf.c
- src/acvp_rsa_prim.c
- src/acvp_util.c
- test/test_acvp_kas_ifc.c
- test/test_acvp_rsa_prim.c
It took a while to debug why some things were failing. some assumptions were made when strcmp and strncmp were being added to the stub that arent in line with the exact parameters we expect. Slight changes there. The command line parser also had a character limit that was too low (was higher internally). The rest are updates already in internal. Will resolve conflicts momentarily.
> Fixes to safeC stub, updating all changes from internal

- test/Makefile.am
- test/Makefile.in
The sandbox-gmon files were actually profile data files; when I revamped the build system a bit -p found its way into the test make data.
This was also causing valgrind to throw some harmless warnings during runs.
We still use debugging symbols with -g though.
> Fixing criterion testing issues

- app/app_main.c
- include/acvp/acvp.h
- include/acvp/acvp_lcl.h
- src/acvp.c
- src/acvp_operating_env.c
- src/acvp_transport.c
- test/test_acvp_operating_env.c
- Removes kas_kdf enable from NO_DSA block
- moves most network activity logging to verbose
- Fixes issue with OE/dependency lookup requiring a description, checks more fields
- Adds and expands some log lines to metadata lookup (more to come)
- Remove fips_metadata_ready for being redundant and move its checks to acvp_operating_env function calls
- Some misc changes
...
- Upcoming: 
- Many more additions to "info" level logging (That contains interesting/useful info, instead of truncated network logging) 
- work on build system if necessary 
- big documentation updates
> Misc. updates and fixes

- app/app_hmac.c
- configure
- configure.ac
- test/Makefile.am
- test/Makefile.in
Some cases were having issues with this. Add check to not add ldl for android builds, because some configs have problems with that. Tested on most internal pipeline platforms.
> Fix LDL setting for offline builds

- app/app_hmac.c
- configure
- configure.ac
- test/Makefile.am
- test/Makefile.in
Reverts the PR that made changes to ldl flagging and such. These worked for some cases, but caused some issues elsewhere. For now, static SSL libs to be used with acvp should be built with no-dso and preferably no-threads to minimize clashes while we work out something long term.
> Revert "Fix LDL setting for offline builds"

- app/Makefile.am
- app/Makefile.in
- app/app_main.c
- app/libacvp_app.h
- configure
- configure.ac
Using configure option --enable-wrapper-library, builds acvp_app as libacvp_app. This can then be used as a single API library (acvp_app_run_vector_test_file) to easily link into more proprietary build systems (such as xcode) without having to constantly maintain an app codebase for the sole purpose of running a test file.
This is meant to be used with --enable-offline. I will disable allowing it to be used with online builds (it builds fine, but is pointless) in the next PR with some other things.
> Added app wrapper code

- app/app_kas_kdf.c
- app/app_lcl.h
- app/app_utils.c
Fixed an issue on big-endian platforms for kas-kdf. Every other value is expected to be big endian, except the counter for hkdf, which is supposed to be little endian. The check was never there for endianness, so it worked fine on little endian platforms.
added loop breaks for when the total concatenated output is greater than the length of output for the test case. this increases the processing speed for onestep KDF by several multitudes.
Renamed function to indicate its used to swap endianness instead of just convert to little endian.
> Fixes and improvements to kas-kdf

- include/acvp/acvp_lcl.h
- src/acvp.c
- src/acvp_operating_env.c
Most of these changes were already committed to 1.4.0 throttle (Some small other changes were also made; I will merge them later)
These changes make dependency lookup align much more closely with the spec (e.g. only name is required; all other fields are optional)
> Fixed some metadata bugs, organized some code, added some logging (1.3.0)

- README.md
- app/app_cli.c
- app/ketopt.h
- Multiple changes to CLI arguments, without changing any current functionality:
- Ketopt will no longer view extra characters in short options as parameters
- any short options longer than 2 characters (-X) are considered invalid
- Improved error output for tons of edge cases for CLI arguments
- Added several new short options that function identically to their counterparts:
- `-r` can be used in place of --vector_req
- `-p` can be used in place of --vector_rsp
- `-u` can be used in place of --vector_upload
- `-s` can be used in place of --save-to
- Replaced if statements in CLI parsing code with switch case. Note that strict cflags do not complain as those warnings are specific to enumerators.
- Relocated much common code to separate functions in app_cli.c
- Many readme updates, …
> Substantial readme and CLI parsing updates

- app/app_cli.c
- app/ketopt.h
- include/acvp/acvp_lcl.h
- include/acvp/parson.h
- src/acvp.c
- src/acvp_build_register.c
- src/parson.c
Note that as we made numerous changes to the parson implementation, the differences had to be resolved entirely by hand (git could not cope), so please let me know if you see any issues. Build passes with no warnings even with stricter cflags.
Also enabled the previously-disabled parson API json_value_deep_copy. This is useful in cases where we may want a JSON sub value, but we dont want to run into issues freeing the root value (case in point, the registration array value).
Also added a new short option, -a, for --all_algs.
The registration is now added to the test session file. This can make the file 100-200KB. this is a rather drastic increase, but I think the addition can save a huge headache for users trying to debug their runs or just keep better tabs on their data.
> Updated parson to 1.1.3, Added registration to testSession file

- include/acvp/acvp.h
This is the first of several PRs designed to improve/overhaul the existing documentation for libacvp. There are very few changes to the actual descriptions in this PR, though there are a few near the top (e.g. log level descriptions). 
acvp.h used multiple styles of comment blocks (alternating between javadoc and Qt style). Many enums were missing `@enum` descriptors, or used `@struct` descriptors. Spacing and line lengths were inconsistent. Some areas had a leading asterisk on each line, others didnt.
This unifies all of the existing documentation. We use Javadoc style for it all now. Each line leads with an asterisk. Each line gets as close to 100 chars as possible. many `@struct` blocks were corrected to `@enum` and many new `@enum` blocks were added.
Finally, the leading whitespace …
> Drastic overhaul for doc formatting in acvp.h

- app/app_cli.c
- ms/resources/acvp_app.vcxproj
- safe_c_stub/src/safe_str_stub.c
SafeC stub did not perform any validation on strnlen; it now checks for null/0 length to match what we'd expect.
Checked for presence of opt.arg before checking strnlen.
Windows: Added missing check for ACV_KDF_SUPPORT (set by make_app.bat) to all configurations for acvp_app; not sure when these went missing.
> Fix cli issue, fix windows issue

- app/app_cli.c
- include/acvp/acvp_lcl.h
- src/acvp.c
When running version command in no-runtime mode, the output will now look similar to this:
```
ACVP library version(protocol version): libacvp_oss-1.4.0(1.0)
Runtime mode: no
FIPS module version: FIPS 2.0.16 validated module 24 Apr 2017
Compiled SSL version: OpenSSL 1.0.2u-fips  20 Dec 2019
Linked SSL version: OpenSSL 1.0.2u-fips  20 Dec 2019
```
When running in runtime mode, it will look similar to this. We dont set FIPS mode in runtime mode, but I feel it is worth communicating that fact to people.
```
ACVP library version(protocol version): libacvp_oss-1.4.0(1.0)
Runtime mode: yes
FIPS mode: no
Compiled SSL version: OpenSSL 1.0.2u-fips  20 Dec 2019
Linked SSL version: OpenSSL 1.0.2u-fips  20 Dec 2019
```
I did not change the acvp version string itself in case ours or other people's …
> Add SSL/FOM info to version command, save request URLs to testSession file

- .lift/config.toml
- .lift/setup.sh
- .muse/config
The MuseDev product has been rebranded to Lift. This MR migrates and updates the tool's configuration file.
> Update Muse to Lift config and use sudo

- .lift/config.toml
- .lift/setup.sh
- .muse/config
- app/app_kdf.c
- app/app_lcl.h
- app/app_main.c
- include/acvp/acvp.h
- include/acvp/acvp_lcl.h
- src/Makefile.am
- src/Makefile.in
- src/acvp.c
- src/acvp_build_register.c
- src/acvp_capabilities.c
- src/acvp_kdf_tls12.c
Due to the nature of the name/mode/revision change as well as the testing change in the new TLS 1.2 KDF revision, I opted to make it into a new cipher that largely replicates the old 1.2 KDF testing. Added warnings to the old cipher (which has been left in for now) that it will be no longer supported come 2022.
Some changes were made to the library side to make it more closely resemble TLS 1.3 KDF for the sake of consistency.
> Add support for TLS 1.2 KDF

- app/app_kas_kdf.c
- src/acvp_kas_kdf.c
Added  app_fips_lcl.h for kas-kdf. Accidentally left it out when backporting.
saltLen missing on NIST server. Opened an issue, but need to do this release. Using a temporary workaround for now.
> Fixes for KAS-KDF

- src/acvp_capabilities.c
- src/acvp_kas_kdf.c
Fix complaint about uninitialized var (generally, trying to make a habit of initializing all to 0 for now) for saltLen
Change to DSA switch case for an internal extended cflag complaint
> Misc. fixes

- metadata/Pipfile.lock
Spending just a bit more time on determining what versions and such to push python and all of the dependencies to, but getting this vulnerability cleared out for now for the upcoming release.
> Update urlib3 to non-vulnerable version

- app/app_kas.c
- app/app_main.c
- src/acvp_build_register.c
- src/acvp_kas_ecc.c
- src/acvp_kas_ffc.c
- src/acvp_kas_ifc.c
- test/test_app_kas_ecc.c
- test/test_app_kas_ffc.c
- test/test_app_kas_ifc.c
Also some misc. other changes/fixes (e.g. no longer including un-needed values for VAL test submissions, spacing)
> Add support for not using a hash algorithm for Z in KAS SSC algorithms

- src/acvp.c
Not all acvp functions currently go through acvp_run, (e.g. resume session) so user_agent is not reliably set this way. Moving it to set server, which is a requirement to run any network traffic through libacvp.
> Move user_agent handler from acvp_run to acvp_set_server

- app/app_hmac.c
- app/app_utils.c
Due to uncertainty around release schedules pushing this to a new libacvp_1_TBD_throttle branch currently.
This is not expected to build currently on 3.0 due to autoconf and needing to setup providers in app_main, I will be pushing this work in pieces. I did test the new hmac code to pass a test session in FIPS mode.
If someone wants to test the legacy deprecated APIs I have left in a compiler flag they can use called ACV_LEGACY_HMAC.
> Initial work on 3.0 hmac conversion, removing 1.0.2 support

- configure.ac
if --disable-lib-check is used, we shouldnt look for opensslv.h and assume for now we use 1.1.1.
> Fix small issue with lib detection

- app/app_cmac.c
- app/app_des.c
- app/app_hmac.c
- app/app_main.c
- configure
- configure.ac
- src/acvp.c
Tdes now uses new IV access API. Copies to a buffer instead of providing direct pointer access to CTX.
Updated HMAC/CMAC to stop strict cflags complaining about loss of const.
Updated configure so SSL version check now comes at beginning of library detection phase instead of end. This way we dont try to detect static libraries for SSL 3.0 when enable-offline is used.
Added error check to totp callback, so libacvp doesn't just hang if app returns non-success exit code to library.
> TDES support, misc. mac updates, configure update

- app/app_cmac.c
- app/app_des.c
- app/app_hmac.c
- app/app_main.c
- app/app_rsa.c
- src/acvp.c
- src/acvp_util.c
This is a big PR for a Friday evening, so definitely feel free to let it sit :) 
RSA siggen, sigver, and sigprim now work on SSL 3.0 in runtime FIPS mode.
Some notes:
Some changes will need to be made to the registration to match the SSL cert, mainly around salt lens and PSS padding.
Will have some crashes on older 3.X versions due to https://github.com/openssl/openssl/issues/17075
There are some "still reachable" blocks in very odd places at the end of the session. I'll look at bit more into it.
Libacvp now shows mode of algorithm being tested in logs, or in failing algorithm list.
Also fixed some previously discussed calloc checks.
> RSA Siggen, sigver, and sigprim support for SSL 3.0 at fips runtime

- app/app_main.c
- app/app_rsa.c
- include/acvp/acvp.h
- include/acvp/acvp_lcl.h
- src/acvp_rsa_keygen.c
Improved support for handling different keygen modes (B.3.3, B.3.6) on the library end. There are probably still a few scratches in there to buff out between the different modes and whether the client or server is generating key info. Will revisit those later.
App side now supports OpenSSL 3.0 RSA keyGen, using B.3.6 testing. Thanks for all the help Barry.
> RSA keyGen OpenSSL 3.0 support, library updates

- app/app_main.c
- include/acvp/acvp.h
- include/acvp/acvp_lcl.h
- src/acvp.c
- src/acvp_build_register.c
- src/acvp_capabilities.c
- src/acvp_kda.c
- src/acvp_util.c
This adds initial support for SP800-56Cr2 to the next minor release. Support for Cr1 is still maintained provided you set that parameter.
Still in progress:
- Support for multi-expansion tests (for HKDF and twoStep)
- Support for KDA-twostep in general
> Support for SP800-56Cr2 (1.5.0)

- app/app_kda.c
- app/app_main.c
The fixed info still has to all be combined in advance before the API can consume it. This seems fine.
> Support for HKDF/Onestep KDA in 3.0

- include/acvp/acvp_lcl.h
- src/acvp_capabilities.c
- src/acvp_util.c
As I was adding twostep code (waiting to get some info back), it was clear that code related to iterating through PARAM_LISTs and NAME_LISTs was getting pretty messy. This was being done on a case-by-case basis in acvp_capabilities.c. This adds iterator functions to acvp_utils, and cleans up all those calls in acvp_capabilities, saving us a few hundred lines of code.
> Cleanup acvp_capabilities list code (1.5.0)

- app/app_drbg.c
- app/app_main.c
Works with most of the registration of OpenSSL 3.0. Todo: library adjustments to be able to test counter DRBG with derivation function and without in the same test session. Putting that on the backburner for time being.
> DRBG support on 3.0

- app/app_main.c
- include/acvp/acvp.h
- src/acvp_build_register.c
- src/acvp_capabilities.c
- AES ciphers that have to indicate whether they support internal or external iv generation can now indicate "either". currently, the server requires that this generates two different vector sets for that particular cipher, so these AES ciphers will appear in the registration twice.
- Updates existing AES registration to match OpenSSL cert
- Fixes some library side validation
> Updates to AES registration and some library fixes

- app/app_drbg.c
- app/app_main.c
- include/acvp/acvp.h
- include/acvp/acvp_lcl.h
- src/acvp.c
- src/acvp_build_register.c
- src/acvp_capabilities.c
- src/acvp_util.c
NOTE: Front-end API changes. This release will probably become 2.0.
Added support for different "groups" of parameters on a per-mode basis for DRBG. This means that a DRBG mode, for example AES-128 CTR, can have two different groups of parameters (in the example, one group with derivation functions enabled, and one without). This required pretty much refactoring the DRBG capability registration system. (As you can see, it was a bit messy). The user now indicates an integer in API calls to specify which group a parameter is being registered for.
Added support for SHA2-512/224 and SHA2-512/256 in Hash and HMAC modes.
> Add group support for DRBG, add truncated SHA mode support

- app/app_kas.c
- app/app_main.c
- include/acvp/acvp.h
- src/acvp_kas_ifc.c
The KAS-IFC testing process (esp. for KAS2) is not super well documented; and the inputs/outputs can vary wildly. It took A LOT of iterating to get to where this is now.
The only way to sanely implement this was to separate out IUT and server key variables; this has been done. So not all variables are always used. 
For KAS2, we handle Z concatenation in the library. SSC shouldn't really cover HOW the two secrets are combined, as those seem to be outside the scope of SSC according to the ACVP spec (that being said, all of the schemes defined in SP800-56Br2 currently use concatenation). 
Tried to add as much clarification to harness with comments as possible. 
I've been staring at this for too long now, apologies if I have missed any obvious typos or such.
> Partial refactor of KAS-IFC, add support for KAS2

- app/app_ecdsa.c
- app/app_main.c
- include/acvp/acvp.h
- include/acvp/acvp_lcl.h
- src/acvp_build_register.c
- src/acvp_capabilities.c
- src/acvp_ecdsa.c
More registration updates to match 3.0 cert, small fix for DRBG registration building, and support for ECDSA siggen/sigver component test.
Note that component test support requires an entire other vector set, instead of supporting both types of test in one vector set like usual.
> ECDSA component test support, more registration updates

- app/app_main.c
- include/acvp/acvp_lcl.h
- src/acvp.c
- src/acvp_build_register.c
- src/acvp_capabilities.c
Domains in the acvp protocol are defined as a given range, AND/OR a list of specific values. We have had very limited support for giving specific values in libacvp; a single value could be provided in some cases and the code often made you chose between a single value or a range.
Now, a domain object consists of a range and a dynamically allocated list of values, so we have alot more control over that. This was needed to update the KDF108 registration. The only downside is we have to specifically free domains in any capability objects that support setting single values. For now, this has only been updated where needed, but is easy to update moving forward. 
Now, when building registrations, libacvp checks if a range exists (increment != 0), adds that, then iterates through the value list …
> Update domain functionality to support list of values, registration updates

- app/app_cli.c
- app/app_lcl.h
- app/app_main.c
- app/app_utils.c
- configure
- configure.ac
Because all ACVP testing can be done using public APIs in 3.X, we don't need to indicate FIPS mode at build time; we can just assume it is FIPS mode and give the user a run time argument they can use to disable fips (--disable_fips) if they need for some reason.
If FIPS is disabled, a warning is printed + 5 seconds of sleep just to emphasize.
If FIPS is enabled, we do a quick digest to sanity check  of crypto operations (EVP_Q_digest) on the FIPS provider. Otherwise, if something is wrong loading the FIPS provider, we will get a vague error doing something else down the road (usually, generating the TOTP).
> Move FIPS mode decision to runtime from build time

- README.md
- app/app_main.c
- src/acvp_build_register.c
- src/acvp_capabilities.c
I anticipate more readme updates will happen, but definitely feel free to ask for any additions. Added a third column to support table to indicate which algorithms are supported testing using 1.1.1 (with only OpenSSL) and 3.X. I will add a migration guide in the readme soon as well.
Also some misc. fixes for flow control (missing breaks) and taglen ordering.
> Initial readme update, misc. fixes

- include/acvp/acvp.h
- include/acvp/acvp_lcl.h
- src/acvp_build_register.c
- src/acvp_capabilities.c
- src/acvp_kda.c
Note: this fix requires more work for the TBD branch as it supports twostep (this branch does not) and has some structural differences inside the library. That PR will be later (this week).
Previously for HKDF, aux shared secrets were considered to be part of the fixedInfo. This works for onestep, but not for hkdf or twostep. Server now has aux shared secret (t) as a separate entity. In libacvp, registering any value for the hybrid secret param enables it, and sets that value as a length.
> Update KDA implementation to match ACVP updates (1.5.0)

- app/app_cli.c
- app/app_lcl.h
- app/app_main.c
- include/acvp/acvp.h
- include/acvp/acvp_lcl.h
- ms/resources/Source.def
- ms/resources/libacvp.vcxproj
- ms/resources/libacvp.vcxproj.filters
- src/acvp.c
- src/acvp_capabilities.c
- test/test_acvp.c
Added API and app behavior for giving the expected number of vector sets from the current test session registration. This could be useful if a user has a limited number of vector sets available for use with the ACVP server and wants to know in advance what to expect.
Also fixed an MS build error from missing x942 KDF references.
> Added vs count functionality, fixed ms build

- app/app_drbg.c
From https://github.com/cisco/libacvp/pull/753
There were some ACVP test vectors we were trying to parse, which had empty inputs for `entropyInput` in the `otherInput` vectors. The field exists, but the string length is `0`. 
I assume `!tc->pr1_len || !tc->pr2_len` are helping to check if the field exists, but because the length is `0`, this causes DRBG ACVP parsing to fail prematurely.
I found an example of such case here: https://pages.nist.gov/ACVP/draft-vassilev-acvp-drbg.html#section-13-7. Although the example is for `ACVP_DRBG_SHA_256`, such cases do exists for `ACVP_DRBG_AES_128/192/256` as well.
Tested with OpenSSL 1.0.2.
> Fix empty inputs on entropyInput for ctrdrbg

- app/app_cli.c
- app/app_lcl.h
- app/app_main.c
- include/acvp/acvp.h
- include/acvp/acvp_lcl.h
- src/acvp.c
- src/acvp_aes.c
- src/acvp_cmac.c
- src/acvp_transport.c
- src/acvp_util.c
- test/test_acvp_utils.c
- test/ut_common.c
- test/ut_common.h
Previously, the library formatted all output messages with ACVP info before sending it to the application's log handler. Now, we just send a plain message and log level to the application log handler. The exception is "debug" mode, where the library prepends function and line information before sending it to the application.
The application now does some fun color coding for errors and warnings by default. 
The application has simplified formatting for output, e.g. not including line info by default and not including things like [STATUS] or [INFO]
> Change to logging structure, updates to logs in a few places

- app/app_utils.c
- include/acvp/acvp.h
- src/acvp.c
- src/acvp_aes.c
- src/acvp_build_register.c
- src/acvp_des.c
- src/acvp_kda.c
- src/acvp_kdf135_x942.c
- src/acvp_rsa_keygen.c
- src/acvp_util.c
- test/test_acvp.c
- test/test_acvp_aes.c
- test/test_acvp_utils.c
Updated list of return values for ACVP_RESULT. Some have been renamed, some added, some removed. Largest changes started with AES library code; these updates will come in parts.
I expect there will be more return code changes as these updates come through; values will be added as needed as I go through the library.
One of the biggest changes here involves separating ACVP_MISSING/INVALID_ARG from ACVP_TC_MISSING/INVALID_DATA. The more generic "arg" values should be reserved for things like public API calls. 
We also added an "ACVP_INTERNAL_ERR" code. This seems oddly generic, but it is intended to be used in places where the code logically should not be able to fail at all but we still require some sort of handling (e.g. "default" cases in switches where all values are handled).
Added …
> First set of return code updates

- app/app_cli.c
- app/app_lcl.h
- app/app_main.c
- app/app_utils.c
- configure
- configure.ac
- include/acvp/acvp.h
- include/acvp/acvp_lcl.h
- include/acvp/parson.h
- ms/resources/Source.def
- src/acvp.c
- src/acvp_build_register.c
- src/acvp_capabilities.c
- src/parson.c
- test/test_acvp_build_register.c
- new API, acvp_get_current_registration, allows user to get a string of the currently registered capabilities. This is just the json array. using --get_registration in acvp_app will return the string, or save it to a file if used with --save_to.
- Changes to internal handling of registration saving. Manual registration files will now be formatted differently; instead of containing the entire registration payload (e.g. acvVersion), they will just have an array with capability objects inside.
- test cases changes for new structure, lots of extra whitespace removed from test file
- Some consistency changes to configure.ac
- Some cflag warning fixes
> New API to allow getting current registration JSON, other fixes

- ms/acvp_app.sln
- ms/config_windows.bat
- ms/libacvp.sln
- ms/make_app.bat
- ms/make_lib.bat
- ms/resources/Source.def
- ms/resources/acvp_app.vcxproj
- ms/resources/libacvp.vcxproj
- ms/resources/libacvp.vcxproj.filters
- src/acvp_kas_ifc.c
Windows build system had several redundant or unnecessary build options:
SafeC build options removed (they don't apply, always using safeC stub)
Legacy SSL (<= 1.0.2) options removed
static linking options removed (Just support DLLs)
Left in offline mode builds for now.
Fully tested Running OpenSSL 3.0.X tests on windows - success! IDed an issue in KAS-IFC where a test case could output as Passed when It was supposed to fail because diffs from memcmp added up to 0 (this could have happened on any platform but since windows only returns -1/0/1 for memcmp, it made the issue manifest much more quickly and obviously. Took some time to track down!)
Note: changes to MS proj files are typically software generated; any formatting issues or anything there typically aren't from me.
> Updates to MS build system for 2.0

- app/app_cli.c
- app/app_lcl.h
- app/app_main.c
- include/acvp/acvp.h
- ms/resources/Source.def
- src/acvp.c
- src/acvp_build_register.c
- test/test_acvp.c
Rename acvp_set_json_filename to acvp_set_registration_file; original name too vague.
Remove acvp_load_kat_filename; this API seemed to just run a vector set but not save the results off anywhere. 
Make the registration builder log the name and mode of all algorithms when using info level logging.
> API changes, log algorithm list

- app/app_main.c
- include/acvp/acvp.h
- ms/resources/Source.def
- src/acvp.c
- src/acvp_build_register.c
- src/acvp_util.c
Since libacvp runs on many different types of platforms, adding an acvp_sleep API to make things a bit cleaner and avoid extra ifdefs. application code can use as well.
Also included a small optimization to the just added alg name logging code.
> Added sleep API that is platform indepedent

- app/app_main.c
- include/acvp/acvp.h
- include/acvp/acvp_lcl.h
- src/acvp.c
- src/acvp_build_register.c
- src/acvp_capabilities.c
- src/acvp_hash.c
- src/acvp_kda.c
- src/acvp_kdf108.c
- src/acvp_rsa_keygen.c
- src/acvp_util.c
Fix DRBG ptr ref error
Fix AES-GCM min IV length (8->0)
Fix arguments and enum for KTS IFC set scheme function
Set ciphers in KDA TC structs
Add blank line before EOF (some editors complain without it)
> Various bugfixes and capability fixes

- app/app_main.c
- include/acvp/acvp.h
- ms/resources/Source.def
- src/acvp.c
- src/acvp_rsa_keygen.c
- test/test_acvp.c
Previously, to set a save file for a GET we used acvp_set_get_save_file. This was a stopgap added in a minor release. Now that we are doing a major release, just modify the acvp_mark_as_get_only API to accommodate a save file.
Small RSA keygen fix.
> Merge GET apis, rsa fix

- app/app_main.c
- include/acvp/acvp.h
- include/acvp/acvp_lcl.h
- src/acvp.c
- src/acvp_build_register.c
- src/acvp_capabilities.c
- src/acvp_rsa_keygen.c
- src/acvp_rsa_prim.c
- src/acvp_util.c
- RSA SigPrim updated to revision 2.0 (Main change is that can now use multiple modulus lengths)
- RSA DecPrim updated to SP800-56Br2. Changes the structure of the test to be less "guess and check" and more just basic decryption testing. Lots of parsing code and handler call code changes to accommodate
- APP BREAKING CHANGES: updates to prim capability APIs needed to allow new revisions
- Support for the 1.0 revisions is also still enabled due to various edge cases where they could be used. This won't be too difficult to remove down the road if it becomes cumbersome
- Replaced all references to a "default" revision to reference "1.0" revision. Now that many algorithms have many different revisions, a global default no longer makes sense
- UT updates not yet completed
- RSA DecPrim OpenSSL …
> RSA primitive revision updates

- app/app_drbg.c
- include/acvp/acvp_lcl.h
- src/acvp_drbg.c
- src/acvp_hash.c
- src/acvp_rsa_keygen.c
**Output outLen for SHAKE-128 and SHAKE-256 test vectors**
For SHAKE-128 and SHAKE-256, we should output `outLen`.
[Reference](https://pages.nist.gov/ACVP/draft-celi-acvp-sha3.html#section-8.3)
**Output required fields for RSA KeyGen if randPQ B.3.6 used**
For RSA KeyGen with randPQ B.3.6, `xP`, `xP1`, `xP2` and other fields should be outputed.
[Reference](https://pages.nist.gov/ACVP/draft-celi-acvp-rsa.html#section-9.1)
**Fix "!predResistanceEnabled and reseedImplemented" for DRBG**
Reseed the DRBG before first generation.
[Reference](https://pages.nist.gov/ACVP/draft-vassilev-acvp-drbg.html#section-8.1-4.1)
**Update defines for KDA**
Max `z` bit is 65536.
[Reference](https://pages.nist.gov/ACVP/draft-hammett-acvp-kas-kdf-hkdf.html#section-7.3)
> Fix SHAKE, RSA, DRBG and KDA issues

- README.md
- app/app_eddsa.c
Use correct instance for EDDSA operations based on the return value from `get_ed_instance_param()`.
Although `ACVP_EDDSA_SUPPORTS_PREHASH` is false in app_main.c, I thought sample app still can try to use proper instance based on test case.
> Use prehash instance if necessary in EDDSA sample app

- app/app_main.c
- app/app_rsa.c
- include/acvp/acvp.h
- include/acvp/acvp_lcl.h
- src/acvp.c
- src/acvp_build_register.c
- src/acvp_capabilities.c
- src/acvp_rsa_keygen.c
- src/acvp_util.c
This one got a bit messy. The RSA capability registration code is pretty old so I brought it up to speed a little bit. It sill isn't perfect but its a little more consistent; I will make a second pass at it at some point.
- FIPS 186-5 support for RSA. 186-4 support is also maintained.
- Removed storing const string references in the RSA capability object (Just use enums and only pull strings when we are building the registration)
- New API's needed to set mask function for RSA signatures, as the other APIs didnt quite have the right combination of parameters
> FIPS 186-5 support for RSA, misc. RSA updates

- app/app_ecdsa.c
- app/app_eddsa.c
- app/app_main.c
- app/app_rsa.c
- src/acvp_build_register.c
- src/acvp_capabilities.c
- src/acvp_eddsa.c
- Old revision of ECDSA should be 1.0, not 186-4. they are the same thing, just different in how ACVP named it
- static analysis fixes
- build fixes for non 186-5
> ECDSA fixes, SA fixes, build fixes

- app/app_main.c
- app/app_sha.c
- configure
- configure.ac
- src/acvp_build_register.c
- Disable EDDSA for non FIPS186-5 modules
- AES-CBC-CS3 PT len lower bound from 136 to 128 for 3.1.2
- give AES GMAC an IV range instead of a single IV for 3.1.2
- Large data testing for SHA:
- Enabled for SHA3 for 3.0.8 or greater by default
- Enabled for rest of SHA for 3.1.2 or greater by default
- Removed the configure option to enable LDT since its now needed by default
- Add more HMAC modes for KDF sp800-108 for 3.1.2 or greater
- PBKDF: add SHA3 support for 3.1.2 or greater
- KAS-FFC: Add MODP modes back for 3.1.2 or greater
- Safe Primes: Add MODP modes back for 3.1.2 or greater
- ECDSA sigs: add SHA3 for 3.1.2 or greater
- RSA bugfix
More registration updates incoming, just the first batch
> Registration updates

- app/app_kda.c
- app/app_main.c
- src/acvp_util.c
- truncated SHA for PKCS 1.5 rsa sigs
- table C3 added for rsa keygen
- KDA onestep: added ALL aux functions to 3.1.X, kept the small subset for 3.0.X, removed most 1.X.X support
- GMAC registration fix
- KDA onestep aux function fixes
Should have one more PR after this to add KMAC KDF
> More registration updates for 3.1.X

- app/app_kdf.c
- app/app_main.c
- src/acvp_build_register.c
- Enable KMAC SP800-108 KDF for 3.1.2, update harness to support testing
- Add missed HMAC modes for feedback mode
- remove unused memory alloc
> KMAC KDF, other fixes

- app/app_cli.c
- app/app_lcl.h
- app/app_utils.c
- Add code to parse FIPS provider version string, print out in version info
- add code to convert provider version string into an int, disabled for now on open source
- change version command output to be more useful (FIPS mode was not properly read previously, as default properties were not set before running the version command)
- Move version function out of app_cli into app_utils
> Basis for reading provider versions

- app/app_main.c
- include/acvp/acvp.h
- include/acvp/acvp_lcl.h
- src/acvp_build_register.c
- src/acvp_capabilities.c
- test/test_acvp_build_register.c
- test/test_acvp_capabilities.c
- test/test_acvp_drbg.c
it is non breaking/backwards compatible with current API calls
> Add option to use DRBG with prediction resistance on AND off

- app/app_main.c
- include/acvp/acvp.h
- include/acvp/acvp_lcl.h
- src/acvp_rsa_sig.c
- src/acvp_util.c
Also make FIPS186-5 registration block smaller to not exclude necessary rsa keygen values
> Add mask function variable to test cases for rsa

- app/app_sha.c
- src/acvp_hash.c
- Store the XOF output len in the test case structure for more test types. Not sure how we didn't have issues without this.
- Use the DigestFinalXOF API for ALL shake tests, instead of depending on default XOF output length in OpenSSL
> SHAKE updates

- app/app_main.c
- include/acvp/acvp_lcl.h
- src/acvp_rsa_keygen.c
allow up to 8192 modulo for RSA keygen. Make sure pred resist/reseed are enabled for ALL versions of openSSL DRBG.
> RSA allow larger modulo, DRBG fix registration

- app/app_rsa.c
- src/acvp_build_register.c
- Fix pubExpMode for decryption primitive; it used to be an array on the server, now its just a string
- Add a disabled decryption primitive handler; works but OpenSSL does not have a bounds check needed to pass testing
- Update both the decryption primitive and signature primitive handlers to support both CRT AND standard format RSA keys
- The logic hasn't changed due to this, its just the way the variables are fed into the contexts
> RSA Primitive updates

- include/acvp/acvp.h
- include/acvp/acvp_lcl.h
- src/acvp.c
- src/acvp_aes.c
- src/acvp_build_register.c
- src/acvp_capabilities.c
- src/acvp_dsa.c
Two commits -- 
Add tgId and tcId values to all DSA TCs
Add support for AES-FF1 and AES-FF3
AES was validated for Demo vectors against the following library:
https://github.com/mysto/clang-fpe
> Addition for AES-FPE and Update to DSA

- src/acvp_capabilities.c
Preparing 2.1.2 release with TOTP fault fix and DRBG API fix
This makes DRBG capability API ignore hash algorithm when setting prediction resistance or reseed
> Add DRBG API fix to 2.1 branch

- app/app_main.c
- configure
- configure.ac
- ms/acvp_app.sln
- ms/make_app.bat
- ms/resources/Source.def
- ms/resources/acvp_app.vcxproj
- ms/resources/acvp_app.vcxproj.filters
- ms/resources/libacvp.vcxproj
- ms/resources/libacvp.vcxproj.filters
- Windows build system for app restructured to match app code changes and newer OpenSSL versions; currently supports openssl 3+, may support more IuTs later if demand appears
- Remove color logging from windows (Incompatible. Could add windows-specific color code, but they are transitioning between several shells right now so does not seem worth it)
- In the autoconf system: freeBSD shell does not support the "+=" operator; replacing with a more portable syntax
- Todo: Investigate why libcurl seems to hang on network activity when FIPS provider is enabled in Windows (Not likely a libacvp issue, but possible, should ID cause either way)
> Updates windows builds for new app structure; fix freeBSD builds

- app/app_cli.c
- app/app_lcl.h
- app/app_main.c
- app/implementations/openssl/3/iut_kdf.c
- app/implementations/openssl/3/registrations/fp_350.c
- src/acvp_ml_kem.c
- test/Makefile.am
- test/Makefile.in
- test/implementations/openssl/3/test_iut_pbkdf.c
ML-KEM moved "dk" info into test case level instead of test group level; adjusting.
Fix version output command issues (Remove actual logic from CLI parsing too)
Misc. fixes for UTs
Registration fix for OpenSSL 3.5.0 (Minimum input key len is 112)
> Fix for ML-KEM, version output fix, etc

- app/implementations/openssl/3/iut_hash.c
- include/acvp/acvp.h
- include/acvp/acvp_lcl.h
- ms/resources/libacvp.vcxproj
- src/Makefile.am
- src/Makefile.in
- src/acvp_build_register.c
- src/acvp_capabilities.c
- src/acvp_hash.c
- src/acvp_hash_mct.c
This is the first of two PRs to add support for the alternate monte-carlo testing mode for hash for libacvp.
- Adds registration support for MCT version (standard or alternate - standard done by default)
- Moves most MCT logic out of acvp_hash.c into a new source file, acvp_hash_mct.c (minor adjustments as needed)
- Adds common function for MCT test cases to delegate out to the correct MCT functions
- Tested with standard mode which continues to work with no app changes
Next PR will:
- Add actual functions and logic for running the alternate mode
- adjust any existing UTs if needed
> First part of adding alternate MCT support to libacvp

- app/implementations/openssl/3/iut_hash.c
- app/implementations/openssl/3/registrations/fp_350.c
- include/acvp/acvp.h
- include/acvp/acvp_lcl.h
- src/acvp_hash.c
- src/acvp_util.c
- Support for alternate mode for MCT testing
- Whether standard or alternate mode is used depends on the registered message lengths
- Ultimately, alternate mode handles situations where the message length are not certain multiples of the digest size
- In alt mode, throughout the process, if an iteration's message is shorter than the original message (aka the seed), it is padded with 0s at the end. IF its longer, its just truncated.
- For SHA1/2 MCT, we did not do the concatenation step on behalf of the user historically. to maintain backwards compatability, we still do not, but we provide a function that can optionally be used to generate the concatenated message (and also truncate/pad it if needed).
- For SHA1/2, we used hard-coded msg length checks on the A/B/C components, as they were …
> Support for Hash monte-carlo testing alternate mode, some restructuring

- README.md
- app/implementations/jitter_entropy/README.md
- app/implementations/liboqs/README.md
- configure
- configure.ac
- `--with-ssl-dir` can now be provided alongside other IUT link flags. The harness for the other IUT will still be built, but OpenSSL link flags will be integrated, which helps with linking to libcurl or liboqs that is built against OpenSSL.
- Updated README.md to indicate various 2.2.0 changes. 
- Added alg list to implementation README.mds.
- Remove disable-lib-check now that we have more strict dependency linking. All it really did was kick the can down the road and create more error variations.
> Update readme, OpenSSL build rules

- app/implementations/openssl/3/registrations/fp_350.c
- include/acvp/acvp.h
- include/acvp/acvp_lcl.h
- src/acvp.c
- src/acvp_aes.c
- src/acvp_build_register.c
- src/acvp_capabilities.c
- src/acvp_hash.c
- src/acvp_kdf135_ssh.c
- Previously, supported only one IV gen mode per registration, either 8.2.1 or 8.2.2
- A module can support both
- But, a module can also support only certain IV sources (internal or external) on certain modes. so we have to track which sources can be used with which modes
This PR expands on the AES capabilities registration:
- capability object now has a "matrix" of iv mode/source combinations
- enables registration of both modes at once using the traditional param set API
- Adds a new API for specifying a specific combination of an IV source and mode, acvp_cap_sym_cipher_set_iv_modes()
- Backwards compatible with existing API calls
- Written to somewhat-easily expand if more IV modes are added to AES later on
This means, at time of writing, one AES-GCM registration can create up to 4 …
> Add support for multiple combinations of IV sources/modes for AES-GCM and related

- README.md
- app/implementations/openssl/3/iut_aes.c
- app/implementations/openssl/3/iut_cmac.c
- app/implementations/openssl/3/iut_des.c
- app/implementations/openssl/3/iut_drbg.c
- app/implementations/openssl/3/iut_dsa.c
- app/implementations/openssl/3/iut_ecdsa.c
- app/implementations/openssl/3/iut_eddsa.c
- app/implementations/openssl/3/iut_hash.c
- app/implementations/openssl/3/iut_hmac.c
- app/implementations/openssl/3/iut_kas.c
- app/implementations/openssl/3/iut_kda.c
- app/implementations/openssl/3/iut_kdf.c
- app/implementations/openssl/3/iut_kmac.c
- app/implementations/openssl/3/iut_ml_dsa.c
- app/implementations/openssl/3/iut_ml_kem.c
- app/implementations/openssl/3/iut_rsa.c
- app/implementations/openssl/3/iut_slh_dsa.c
- include/acvp/acvp.h
- migration_guide.md
- ms/resources/Source.def
This release is now ready unless any issues are found in remaining testing. 
This PR:
- Organize header 'includes' at top of OpenSSL harness files
- Make OpenSSL harness consistently use "rv" for return values
- Consistently dump OpenSSL errors to stderr if a test claims to have failed
- Add missing APIs to windows build system file
- Misc documentation updates
> Return behavior changes, more fixes

- app/Makefile.am
- app/Makefile.in
- app/app_cli.c
- app/app_lcl.h
- app/implementations/openssl/3/iut.c
- app/implementations/openssl/3/iut.h
- app/implementations/openssl/3/iut_cshake.c
- app/implementations/openssl/3/registrations/fp_4X.c
- include/acvp/acvp.h
- include/acvp/acvp_lcl.h
- src/Makefile.am
- src/Makefile.in
- src/acvp.c
- src/acvp_build_register.c
- src/acvp_capabilities.c
- src/acvp_cshake.c
First commit for 2.3.0. 
- Library support for cSHAKE
- Added initial registration for OpenSSL 4 (copied 3.5 and added cSHAKE)
- Added testing harness for cSHAKE and OpenSSL 4
> Library support for cSHAKE, OpenSSL 4.X harness (2.3.0 branch)

- app/implementations/openssl/3/iut_dsa.c
- app/implementations/openssl/3/iut_ecdsa.c
- safe_c_stub/include/safe_lib_errno.h
- Fix safeC stub headers. Currently, safeC either uses its own errno definitions, OR can be built to use errno.h, assuming that all of safeC's values had been added to errno.h. EINVAL is always going to be defined as part of errno.h, which can cause redefine issues/warnings downstream. Instead of choosing errno.h OR safeC errno codes, lets use errno.h and use ifndef to define any which are not included in errno.h.
- Fix some casting warnings in DSA and ECDSA harnesses for OpenSSL
> Fixes for some strict build warnings
